apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill_collection
  labels:
    app: bill_collection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bill_collection
  template:
    metadata:
      labels:
        app: bill_collection
    spec:
      containers:
        - name: bill_collection
          image: username/bill_collection:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5